/**
 * polarion.js — Siemens Polarion ALM REST API Integration
 * PI Retrospective App — SAFe 6.0
 *
 * Uses the Polarion REST API (available since Polarion 2304/21 R2).
 * API Reference: https://{server}/polarion/rest/v1
 *
 * SECURITY NOTES:
 *  - API tokens are never written to localStorage or SessionStorage.
 *  - The token is only held in a local closure during the active session.
 *  - All requests include minimal required headers only.
 *  - CORS: Production deployments require either:
 *      (a) Polarion CORS configuration, or
 *      (b) A same-origin proxy server.
 *    The browser will block cross-origin requests to Polarion without CORS headers.
 */

'use strict';

const PolarionAPI = (() => {

  // ─── HTML Description Builder ──────────────────────────────────────
  function _buildRetroDescription(retro) {
    const escHtml = s => String(s)
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;')
      .replace(/"/g, '&quot;');

    const section = (title, rows) => rows.length === 0 ? '' : `
<h3>${escHtml(title)}</h3>
<ul>${rows.map(r => `<li>${escHtml(r)}</li>`).join('')}</ul>`;

    const events = (retro.piContext?.events || []).map(e =>
      `${e.date ? `[${e.date}] ` : ''}${e.text}`);

    const milestones = (retro.piContext?.milestones || []).map(m =>
      `[${m.status.toUpperCase()}] ${m.text}${m.date ? ` (${m.date})` : ''}`);

    const specials = (retro.piContext?.specialOccurrences || []).map(s =>
      `[${s.category}] ${s.text}`);

    const wentWell     = (retro.board?.wentWell     || []).map(n => n.text);
    const couldImprove = (retro.board?.couldImprove || []).map(n => n.text);
    const didntGoWell  = (retro.board?.didntGoWell  || []).map(n => n.text);

    const participants = [retro.host, ...(retro.participants || [])]
      .map(p => p.name).join(', ');

    return `<h2>PI Retrospective: ${escHtml(retro.piName)}</h2>
<p><strong>ART:</strong> ${escHtml(retro.artName || '—')} &nbsp;|&nbsp;
   <strong>Period:</strong> ${escHtml(retro.startDate || '?')} to ${escHtml(retro.endDate || '?')} &nbsp;|&nbsp;
   <strong>Participants:</strong> ${escHtml(participants)}</p>

${retro.piObjectives ? `<h3>PI Objectives</h3><p>${escHtml(retro.piObjectives)}</p>` : ''}

<h2>PI Context</h2>
${section('Important Events', events)}
${section('Milestones', milestones)}
${section('Special Occurrences', specials)}

<h2>Retrospective Board</h2>
${section('✅ Went Well', wentWell)}
${section('⬆️ Could Improve', couldImprove)}
${section('❌ Didn\'t Go Well', didntGoWell)}

<p><em>Generated by PI Retrospective App (SAFe 6.0) on ${new Date().toLocaleString()}</em></p>`;
  }

  // ─── Common Fetch Wrapper ──────────────────────────────────────────
  async function _request(method, url, token, body = null) {
    const headers = {
      'Authorization': `Bearer ${token}`,
      'Accept': 'application/json'
    };
    if (body) {
      headers['Content-Type'] = 'application/json';
    }

    let response;
    try {
      response = await fetch(url, {
        method,
        headers,
        body: body ? JSON.stringify(body) : undefined,
        credentials: 'omit' // do not send cookies cross-origin
      });
    } catch (networkError) {
      throw new Error(
        `Network error — cannot reach Polarion server. ` +
        `This may be a CORS issue. Ensure the Polarion server at ${new URL(url).origin} ` +
        `allows cross-origin requests from this origin, or use a same-host proxy.`
      );
    }

    if (!response.ok) {
      let errorDetail = '';
      try {
        const errJson = await response.json();
        errorDetail = errJson?.errors?.[0]?.detail || errJson?.message || '';
      } catch (_) {
        errorDetail = await response.text().catch(() => '');
      }
      throw new Error(
        `Polarion API error ${response.status}: ${response.statusText}` +
        (errorDetail ? ` — ${errorDetail}` : '')
      );
    }

    if (response.status === 204) return null; // No content
    return response.json();
  }

  // ─── Public API ────────────────────────────────────────────────────
  return {

    /**
     * Test the connection to Polarion.
     * @param {Object} cfg — { serverUrl, projectId, token }
     * @returns {Promise<{ok: boolean, projectName: string|null}>}
     */
    async testConnection(cfg) {
      const url = `${cfg.serverUrl.replace(/\/$/, '')}/polarion/rest/v1/projects/${encodeURIComponent(cfg.projectId)}`;
      const data = await _request('GET', url, cfg.token);
      const projectName = data?.data?.attributes?.name || cfg.projectId;
      return { ok: true, projectName };
    },

    /**
     * Push the full retrospective to Polarion:
     *  1. Creates a parent Work Item for the PI Retrospective.
     *  2. Creates child Work Items for each action item (if optPushActions=true).
     *
     * @param {Object} retro      — retrospective data
     * @param {Object} cfg        — { serverUrl, projectId, token, workItemType, parentId, space }
     * @param {Object} opts       — { pushContext, pushBoard, pushActions }
     * @param {Function} onProgress — callback(msg) for progress updates
     * @returns {Promise<{retroWorkItemId: string, actionItemIds: string[]}>}
     */
    async pushRetrospective(retro, cfg, opts = {}, onProgress = () => {}) {
      const baseUrl = cfg.serverUrl.replace(/\/$/, '');
      const projectId = encodeURIComponent(cfg.projectId);
      const wiType = cfg.workItemType || 'task';

      // ── Step 1: Create parent retrospective work item ──
      onProgress('Creating PI Retrospective work item...');

      const includeContext = opts.pushContext !== false;
      const includeBoard   = opts.pushBoard   !== false;

      // Build a filtered retro for description if partial push
      const descRetro = {
        ...retro,
        piContext: includeContext ? retro.piContext : { events: [], milestones: [], specialOccurrences: [] },
        board: includeBoard ? retro.board : { wentWell: [], couldImprove: [], didntGoWell: [] }
      };

      const retroBody = {
        data: {
          type: 'workitems',
          attributes: {
            type: { id: wiType },
            title: `PI Retrospective: ${retro.piName}`,
            description: {
              type: 'text/html',
              value: _buildRetroDescription(descRetro)
            },
            status: { id: 'open' }
          }
        }
      };

      // Attach to space if provided
      if (cfg.space) {
        retroBody.data.attributes.moduleFolder = cfg.space;
      }

      const retroResult = await _request(
        'POST',
        `${baseUrl}/polarion/rest/v1/projects/${projectId}/workitems`,
        cfg.token,
        retroBody
      );

      const retroWorkItemId = retroResult?.data?.id;
      if (!retroWorkItemId) {
        throw new Error('Polarion did not return a Work Item ID for the retrospective. Push may have partially succeeded.');
      }
      onProgress(`Created Work Item: ${retroWorkItemId}`);

      // ── Step 2: Link to parent if supplied ────────────────────────
      if (cfg.parentId) {
        onProgress(`Linking to parent work item ${cfg.parentId}...`);
        try {
          await _request(
            'POST',
            `${baseUrl}/polarion/rest/v1/projects/${projectId}/workitems/${encodeURIComponent(retroWorkItemId)}/linkedworkitems`,
            cfg.token,
            {
              data: [{
                type: 'linkedworkitems',
                attributes: { role: { id: 'parent' } },
                relationships: {
                  workItem: { data: { type: 'workitems', id: cfg.parentId } }
                }
              }]
            }
          );
        } catch (e) {
          // Non-fatal: just warn
          onProgress(`Warning: Could not link to parent — ${e.message}`);
        }
      }

      // ── Step 3: Create action item work items ──────────────────────
      const actionItemIds = [];
      if (opts.pushActions !== false && retro.actionItems?.length) {
        onProgress(`Creating ${retro.actionItems.length} action item work item(s)...`);

        const allParticipants = [retro.host, ...(retro.participants || [])];

        for (const action of retro.actionItems) {
          const assignee = allParticipants.find(p => p.id === action.assigneeId);
          const priorityMap = { critical: 'critical', high: 'high', medium: 'medium', low: 'low' };

          const aiBody = {
            data: {
              type: 'workitems',
              attributes: {
                type: { id: wiType },
                title: action.title,
                description: {
                  type: 'text/html',
                  value: `<p>${(action.description || '').replace(/\n/g, '<br/>')}</p><p><em>Source: PI Retrospective — ${retro.piName}</em></p>`
                },
                priority: { id: priorityMap[action.priority] || 'medium' },
                status: { id: action.status === 'done' ? 'done' : (action.status === 'in-progress' ? 'inProgress' : 'open') },
                dueDate: action.dueDate || undefined
              }
            }
          };

          // Assignee — Polarion uses userId, we store display name.
          // Best effort: set the assignee field with the known name.
          // Users should verify assignments in Polarion.
          if (assignee) {
            aiBody.data.attributes.assignee = [{ id: assignee.name }];
          }

          try {
            const aiResult = await _request(
              'POST',
              `${baseUrl}/polarion/rest/v1/projects/${projectId}/workitems`,
              cfg.token,
              aiBody
            );
            const aiId = aiResult?.data?.id;
            if (aiId) {
              actionItemIds.push(aiId);
              // Link action item to parent retrospective work item
              await _request(
                'POST',
                `${baseUrl}/polarion/rest/v1/projects/${projectId}/workitems/${encodeURIComponent(aiId)}/linkedworkitems`,
                cfg.token,
                {
                  data: [{
                    type: 'linkedworkitems',
                    attributes: { role: { id: 'parent' } },
                    relationships: {
                      workItem: { data: { type: 'workitems', id: retroWorkItemId } }
                    }
                  }]
                }
              ).catch(() => {}); // Non-fatal
            }
          } catch (actionErr) {
            onProgress(`Warning: Could not create action item "${action.title}" — ${actionErr.message}`);
          }
        }
        onProgress(`Created ${actionItemIds.length} action item(s).`);
      }

      return { retroWorkItemId, actionItemIds };
    }
  };
})();
